export const places = [
  {
    name: "The Spicy Spoon",
    address: "123 Hot Sauce Ave, Sydney, NSW",
    latLng: { latitude: -33.8688, longitude: 151.2093 },
    rating: 8,
    visited: true,
  },
  {
    name: "Bistro Bella",
    address: "456 Olive St, Melbourne, VIC",
    latLng: { latitude: -37.8136, longitude: 144.9631 },
    rating: 7,
    visited: false,
  },
  {
    name: "The Rustic Table",
    address: "789 Country Rd, Perth, WA",
    latLng: { latitude: -31.9505, longitude: 115.8605 },
    rating: 9,
    visited: true,
  },
  {
    name: "Urban Eats",
    address: "321 Market Ln, Adelaide, SA",
    latLng: { latitude: -34.9285, longitude: 138.6007 },
    rating: 6,
    visited: false,
  },
  {
    name: "Seaside Grill",
    address: "654 Ocean Blvd, Gold Coast, QLD",
    latLng: { latitude: -28.0167, longitude: 153.4 },
    rating: 8,
    visited: true,
  },
  {
    name: "Mountain View Cafe",
    address: "987 Alpine Dr, Hobart, TAS",
    latLng: { latitude: -42.8821, longitude: 147.3272 },
    rating: 7,
    visited: false,
  },
  {
    name: "Sunset Diner",
    address: "246 Sunset Blvd, Canberra, ACT",
    latLng: { latitude: -35.2809, longitude: 149.13 },
    rating: 5,
    visited: true,
  },
  {
    name: "The Green Garden",
    address: "135 Nature St, Darwin, NT",
    latLng: { latitude: -12.4634, longitude: 130.8456 },
    rating: 9,
    visited: false,
  },
  {
    name: "City Lights Bar & Grill",
    address: "753 Downtown Ave, Brisbane, QLD",
    latLng: { latitude: -27.4698, longitude: 153.0251 },
    rating: 6,
    visited: true,
  },
  {
    name: "Harbour View Restaurant",
    address: "159 Dockside Rd, Sydney, NSW",
    latLng: { latitude: -33.8548, longitude: 151.2165 },
    rating: 8,
    visited: true,
  },
  {
    name: "The Steak House",
    address: "951 Carnivore Ln, Geelong, VIC",
    latLng: { latitude: -38.1499, longitude: 144.3617 },
    rating: 7,
    visited: false,
  },
  {
    name: "Pizza Palace",
    address: "357 Slice St, Perth, WA",
    latLng: { latitude: -31.9486, longitude: 115.8575 },
    rating: 5,
    visited: true,
  },
  {
    name: "Curry Corner",
    address: "258 Spice Ave, Adelaide, SA",
    latLng: { latitude: -34.9279, longitude: 138.5987 },
    rating: 9,
    visited: true,
  },
  {
    name: "The Fish Market",
    address: "469 Sea Ln, Gold Coast, QLD",
    latLng: { latitude: -28.0017, longitude: 153.398 },
    rating: 6,
    visited: false,
  },
  {
    name: "Noodle House",
    address: "741 Asian Way, Sydney, NSW",
    latLng: { latitude: -33.865, longitude: 151.2094 },
    rating: 8,
    visited: true,
  },
  {
    name: "Burger Barn",
    address: "852 Patty Rd, Darwin, NT",
    latLng: { latitude: -12.4624, longitude: 130.8416 },
    rating: 7,
    visited: true,
  },
  {
    name: "Vegan Vibes",
    address: "369 Plant St, Melbourne, VIC",
    latLng: { latitude: -37.814, longitude: 144.9633 },
    rating: 9,
    visited: false,
  },
  {
    name: "The Smokehouse",
    address: "963 Grill Ave, Brisbane, QLD",
    latLng: { latitude: -27.4668, longitude: 153.0211 },
    rating: 6,
    visited: true,
  },
  {
    name: "Ocean Breeze Cafe",
    address: "147 Shoreline Dr, Cairns, QLD",
    latLng: { latitude: -16.9186, longitude: 145.7781 },
    rating: 8,
    visited: true,
  },
  {
    name: "Taco Town",
    address: "258 Fiesta Ln, Newcastle, NSW",
    latLng: { latitude: -32.9283, longitude: 151.7817 },
    rating: 7,
    visited: false,
  },
  {
    name: "The Pasta Place",
    address: "369 Noodle St, Perth, WA",
    latLng: { latitude: -31.9466, longitude: 115.8555 },
    rating: 5,
    visited: true,
  },
  {
    name: "The Dessert Den",
    address: "951 Sweet St, Adelaide, SA",
    latLng: { latitude: -34.9259, longitude: 138.5967 },
    rating: 9,
    visited: true,
  },
  {
    name: "Tapas & More",
    address: "753 Tapas Blvd, Sydney, NSW",
    latLng: { latitude: -33.8682, longitude: 151.2097 },
    rating: 6,
    visited: false,
  },
  {
    name: "Sushi Station",
    address: "159 Wasabi Way, Melbourne, VIC",
    latLng: { latitude: -37.8142, longitude: 144.9634 },
    rating: 8,
    visited: true,
  },
  {
    name: "Barbecue Barn",
    address: "246 Grill Rd, Hobart, TAS",
    latLng: { latitude: -42.8806, longitude: 147.3248 },
    rating: 7,
    visited: false,
  },
  {
    name: "Mediterranean Magic",
    address: "135 Olive Rd, Sydney, NSW",
    latLng: { latitude: -33.9195, longitude: 151.2336 },
    rating: 9,
    visited: true,
  },
  {
    name: "Breakfast Bliss",
    address: "753 Egg St, Brisbane, QLD",
    latLng: { latitude: -27.4689, longitude: 153.0255 },
    rating: 6,
    visited: true,
  },
  {
    name: "The Cozy Cafe",
    address: "357 Warm St, Sydney, NSW",
    latLng: { latitude: -33.847, longitude: 151.2115 },
    rating: 8,
    visited: false,
  },
  {
    name: "Bistro 360",
    address: "852 Spin Ln, Canberra, ACT",
    latLng: { latitude: -35.2803, longitude: 149.131 },
    rating: 7,
    visited: true,
  },
  {
    name: "Taste of Thai",
    address: "147 Curry Ln, Darwin, NT",
    latLng: { latitude: -12.4636, longitude: 130.8428 },
    rating: 5,
    visited: false,
  },
];
